name: Test and Coverage Check

on:
  pull_request:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run tests with coverage
        run: yarn run test:cov
